name: pull request test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  
  pull_request:
    branches:
      - develop
  schedule:
    # every midnight (utc time)
    - cron:  '0 0 * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Update Api
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }} 
        run: echo GOOGLE_MAPS_API_KEY="$GOOGLE_MAPS_API_KEY" > ./local.properties
        
      - name: Run detekt
        run: ./gradlew detekt
        
      - name: Run build
        run: |
          ./gradlew clean build
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./build/jacoco
          verbose: true # optional (default = false)
  

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: Test report
          path: robot/tests/report.html
          
      - name: Start Unit Tests
        run: ./gradlew testDebugUnitTest
